secrets:
  mongodb_uri:
    file: ./mongodb_uri.txt #Added secrets to hide backen

services:
  web:
    build: .
    secrets:
      - mongodb_uri
    environment:
      NODE_ENV: production
      MONGODB_URI: /run/secrets/mongodb_uri
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    user: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
